version: '3.7'
services:
  pozos:
    image: pozos:v1
    container_name: pozos
    ports:
      - 80:5000
    volumes:
      - ./student-list/simple_api:/data/
    networks:
      - liaison_interne
  
  PHP:
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    ports:
      - 8000:80
    volumes:
      - ./student-list/website:/var/www/html
    depends_on:
      - pozos
    networks:
      - liaison_interne
  registry:
    image: registry:2.7
    volumes:
      - ./registry-data:/var/lib/registry
    ports:
      - 5000:5000
    networks:
      - pozos_registry

  registry_ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 4000:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
      - SHOW_CONTENT_DIGEST=true
    depends_on:
      - registry
    networks:
      - pozos_registry
networks:
  pozos_registry:
  liaison_interne: